---
version: "3.9"

services:

  devopsdb:
    image: shobha722/automation:db

    ports:
      - "3306:3306"

    deploy:
      replicas: 1

    networks:
      - mynetwork

  application:
    image: shobha722/automation:app

    ports:
      - "1234:8080"

    depends_on:
      - devopsdb

    deploy:
      replicas: 1

    networks:
      - mynetwork

networks:
  mynetwork:
    driver: overlay


   
